# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b73eeb73a0a971b00dc0d53df0093e4b89b43a7267704cf7204088730712ec62bd094225c49be4d87ba1af104fc54f820c8021905a9114c6bb3f29ce3271dcaf

test:
  secret_key_base: 38eed3b6aec93d37abfc5e230d2dd63f8ed122343f0d53e154ad587eda30f50b87c9767f937d3067da5418c1bb9760ad17d7e9b04e0b3aeccd3ccb1a51e6d97b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
